version: '3'
services:
  laptop-mall-db:
    container_name: laptop-mall-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=LaptopMall
    ports:
      - "5432:5432"
    volumes:
      - laptop-mall-data:/var/lib/postgresql

volumes:
  laptop-mall-data: